/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as KanbanRouteImport } from './routes/kanban'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TasksIndexRouteImport } from './routes/tasks.index'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as KanbanIndexRouteImport } from './routes/kanban.index'
import { Route as TasksProjectIdRouteImport } from './routes/tasks.$projectId'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as KanbanProjectIdRouteImport } from './routes/kanban.$projectId'

const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const KanbanRoute = KanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIndexRoute = TasksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TasksRoute,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsRoute,
} as any)
const KanbanIndexRoute = KanbanIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KanbanRoute,
} as any)
const TasksProjectIdRoute = TasksProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => TasksRoute,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => ProjectsRoute,
} as any)
const KanbanProjectIdRoute = KanbanProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => KanbanRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/kanban': typeof KanbanRouteWithChildren
  '/projects': typeof ProjectsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRouteWithChildren
  '/kanban/$projectId': typeof KanbanProjectIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/tasks/$projectId': typeof TasksProjectIdRoute
  '/kanban/': typeof KanbanIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/tasks/': typeof TasksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/settings': typeof SettingsRoute
  '/kanban/$projectId': typeof KanbanProjectIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/tasks/$projectId': typeof TasksProjectIdRoute
  '/kanban': typeof KanbanIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/tasks': typeof TasksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/kanban': typeof KanbanRouteWithChildren
  '/projects': typeof ProjectsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRouteWithChildren
  '/kanban/$projectId': typeof KanbanProjectIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/tasks/$projectId': typeof TasksProjectIdRoute
  '/kanban/': typeof KanbanIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/tasks/': typeof TasksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/kanban'
    | '/projects'
    | '/settings'
    | '/tasks'
    | '/kanban/$projectId'
    | '/projects/$projectId'
    | '/tasks/$projectId'
    | '/kanban/'
    | '/projects/'
    | '/tasks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/settings'
    | '/kanban/$projectId'
    | '/projects/$projectId'
    | '/tasks/$projectId'
    | '/kanban'
    | '/projects'
    | '/tasks'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/kanban'
    | '/projects'
    | '/settings'
    | '/tasks'
    | '/kanban/$projectId'
    | '/projects/$projectId'
    | '/tasks/$projectId'
    | '/kanban/'
    | '/projects/'
    | '/tasks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  KanbanRoute: typeof KanbanRouteWithChildren
  ProjectsRoute: typeof ProjectsRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  TasksRoute: typeof TasksRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kanban': {
      id: '/kanban'
      path: '/kanban'
      fullPath: '/kanban'
      preLoaderRoute: typeof KanbanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/': {
      id: '/tasks/'
      path: '/'
      fullPath: '/tasks/'
      preLoaderRoute: typeof TasksIndexRouteImport
      parentRoute: typeof TasksRoute
    }
    '/projects/': {
      id: '/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/kanban/': {
      id: '/kanban/'
      path: '/'
      fullPath: '/kanban/'
      preLoaderRoute: typeof KanbanIndexRouteImport
      parentRoute: typeof KanbanRoute
    }
    '/tasks/$projectId': {
      id: '/tasks/$projectId'
      path: '/$projectId'
      fullPath: '/tasks/$projectId'
      preLoaderRoute: typeof TasksProjectIdRouteImport
      parentRoute: typeof TasksRoute
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/kanban/$projectId': {
      id: '/kanban/$projectId'
      path: '/$projectId'
      fullPath: '/kanban/$projectId'
      preLoaderRoute: typeof KanbanProjectIdRouteImport
      parentRoute: typeof KanbanRoute
    }
  }
}

interface KanbanRouteChildren {
  KanbanProjectIdRoute: typeof KanbanProjectIdRoute
  KanbanIndexRoute: typeof KanbanIndexRoute
}

const KanbanRouteChildren: KanbanRouteChildren = {
  KanbanProjectIdRoute: KanbanProjectIdRoute,
  KanbanIndexRoute: KanbanIndexRoute,
}

const KanbanRouteWithChildren =
  KanbanRoute._addFileChildren(KanbanRouteChildren)

interface ProjectsRouteChildren {
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

interface TasksRouteChildren {
  TasksProjectIdRoute: typeof TasksProjectIdRoute
  TasksIndexRoute: typeof TasksIndexRoute
}

const TasksRouteChildren: TasksRouteChildren = {
  TasksProjectIdRoute: TasksProjectIdRoute,
  TasksIndexRoute: TasksIndexRoute,
}

const TasksRouteWithChildren = TasksRoute._addFileChildren(TasksRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  KanbanRoute: KanbanRouteWithChildren,
  ProjectsRoute: ProjectsRouteWithChildren,
  SettingsRoute: SettingsRoute,
  TasksRoute: TasksRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
